import os
import pygame

PROJECT_PATH = os.path.abspath(os.path.join(__file__, '../..'))
IMAGE_PATH = os.path.join(PROJECT_PATH, 'images')

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# SCREEN_WIDTH = 1920
# SCREEN_HEIGHT = 1080

WORLD_WIDTH = 5000
WORLD_HEIGHT = 5000

SCREEN_CENTER_X = SCREEN_WIDTH/2
SCREEN_CENTER_Y = SCREEN_HEIGHT/2
WORLD_BOUNDS = pygame.Rect((-WORLD_WIDTH/2 + SCREEN_CENTER_X,-WORLD_HEIGHT/2 + SCREEN_CENTER_Y), (WORLD_WIDTH, WORLD_HEIGHT))

MIN_CREATURE_AMOUNT = 5

MAX_ENERGY_MULT = 20 # max_energy = mass * MAX_ENERGY_MULT
BOOSTER_ENERGY_USAGE = 0.1
BASE_ENERGY_DRAIN = 2 / 1000

REP_ENERGY_COST_MULT = 2 # reproduction_cost = mass * REP_ENERGY_COST_MULT

REP_PROB = 0.2 # chance to reproduce when eating banana

INVINCIBILITY_TIME = 60 # frames

BANANA_ENERGY_GAIN = 80

MAX_BANANAS = 5000
BANANA_SPAWN_COOLDOWN = 1 # frames

# mutations
TEST_PROB_MULT = 1

MOVE_JOINT_PROB = 0.10
AVG_JOINT_MOVE_AMOUNT = 5

ADD_JOINT_PROB = 0.03
NEW_JOINT_DIST = 15

ADD_BONE_PROB = 0.03
REMOVE_BONE_PROB = 0.06

MIN_PART_SIZE = 5
PART_PADDING = 6

MOVE_PART_PROB = 0.05
AVG_PART_MOVE_AMOUNT = 5

RESIZE_PART_PROB = 0.05
AVG_PART_RESIZE_AMOUNT = 3

ADD_PART_PROB = 0.01
REMOVE_PART_PROB = 0.01